// <auto-generated />
using System;
using EasyTime.InfraStracure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyTime.InfraStracure.Migrations
{
    [DbContext(typeof(EasyTimeContext))]
    [Migration("20250701171459_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessOwnerDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BusinessOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinesOwnerDays");
                });

            modelBuilder.Entity("BusinessOwnerTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<long>("BusinessOwnerDayId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("From")
                        .HasColumnType("time");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("To")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessOwnerDayId");

                    b.ToTable("BusinesOwnerTimes");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesCity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BusinesCityes");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesNeighberhood", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinesRegionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinesRegionId");

                    b.ToTable("BusinesNeighberhoodes");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesRegion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinesCityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinesCityId");

                    b.ToTable("BusinesRegiones");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Business", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BusinesOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NeighberhoodId")
                        .HasColumnType("bigint");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BusinesOwnerId");

                    b.HasIndex("CityId");

                    b.HasIndex("NeighberhoodId");

                    b.HasIndex("RegionId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Reserve", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessOwnerDayId")
                        .HasColumnType("bigint");

                    b.Property<long>("BusinessOwnerTimeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BusinessOwnerDayId");

                    b.HasIndex("BusinessOwnerTimeId");

                    b.ToTable("Reserves");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EasyTime.Model.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpireChangePasswordToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBusinesOwner")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TokenForChangePassword")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessOwnerDay", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Business", "Business")
                        .WithMany("BusinessOwnerDays")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BusinessOwnerTime", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Business", "Business")
                        .WithMany("BusinessOwnerTimes")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessOwnerDay", "BusinessOwnerDay")
                        .WithMany("BusinessOwnerTimes")
                        .HasForeignKey("BusinessOwnerDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("BusinessOwnerDay");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesNeighberhood", b =>
                {
                    b.HasOne("EasyTime.Model.Models.BusinesRegion", "BusinesRegion")
                        .WithMany()
                        .HasForeignKey("BusinesRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinesRegion");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesRegion", b =>
                {
                    b.HasOne("EasyTime.Model.Models.BusinesCity", "BusinesCity")
                        .WithMany("BusinesRegions")
                        .HasForeignKey("BusinesCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinesCity");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Business", b =>
                {
                    b.HasOne("EasyTime.Model.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("BusinesOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyTime.Model.Models.BusinesCity", "BusinesCity")
                        .WithMany("Businesses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyTime.Model.Models.BusinesNeighberhood", "BusinesNeighberhood")
                        .WithMany("Businesses")
                        .HasForeignKey("NeighberhoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyTime.Model.Models.BusinesRegion", "BusinesRegion")
                        .WithMany("Businesses")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinesCity");

                    b.Navigation("BusinesNeighberhood");

                    b.Navigation("BusinesRegion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Reserve", b =>
                {
                    b.HasOne("BusinessOwnerDay", "BusinessOwnerDay")
                        .WithMany("Reserves")
                        .HasForeignKey("BusinessOwnerDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessOwnerTime", "BusinessOwnerTime")
                        .WithMany("Reserves")
                        .HasForeignKey("BusinessOwnerTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessOwnerDay");

                    b.Navigation("BusinessOwnerTime");
                });

            modelBuilder.Entity("EasyTime.Model.Models.User", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessOwnerDay", b =>
                {
                    b.Navigation("BusinessOwnerTimes");

                    b.Navigation("Reserves");
                });

            modelBuilder.Entity("BusinessOwnerTime", b =>
                {
                    b.Navigation("Reserves");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesCity", b =>
                {
                    b.Navigation("BusinesRegions");

                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesNeighberhood", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesRegion", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Business", b =>
                {
                    b.Navigation("BusinessOwnerDays");

                    b.Navigation("BusinessOwnerTimes");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
