// <auto-generated />
using System;
using EasyTime.InfraStracure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyTime.InfraStracure.Migrations
{
    [DbContext(typeof(EasyTimeContext))]
    [Migration("20250808110941_CreateTableBusinessService")]
    partial class CreateTableBusinessService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessOwnerDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BusinessOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinesOwnerDays");
                });

            modelBuilder.Entity("BusinessOwnerTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<long>("BusinessOwnerDayId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("From")
                        .HasColumnType("time");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("To")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessOwnerDayId");

                    b.ToTable("BusinesOwnerTimes");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesCity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BusinesCityes");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesNeighberhood", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinesRegionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinesRegionId");

                    b.ToTable("BusinesNeighberhoodes");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesRegion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinesCityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinesCityId");

                    b.ToTable("BusinesRegiones");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Business", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BusinessOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NeighberhoodId")
                        .HasColumnType("bigint");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessOwnerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("NeighberhoodId");

                    b.HasIndex("RegionId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinessDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DayId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("DayId");

                    b.ToTable("BusinessDays");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinessOwnerPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpire")
                        .HasColumnType("bit");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlanTimeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("PlanTimeId");

                    b.HasIndex("UserId");

                    b.ToTable("BusinessOwnerPlans");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinessServices", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BusinessServices");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinessTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessDayId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<long>("TimeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDayId");

                    b.HasIndex("TimeId");

                    b.ToTable("BusinessTimes");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Plan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("BasePrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PlanTimeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanTimeId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("EasyTime.Model.Models.PlanTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("AmountAdded")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlanTimes");
                });

            modelBuilder.Entity("EasyTime.Model.Models.PlansInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlanService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlansInformation");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Reserve", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessOwnerDayId")
                        .HasColumnType("bigint");

                    b.Property<long>("BusinessOwnerTimeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BusinessOwnerDayId");

                    b.HasIndex("BusinessOwnerTimeId");

                    b.ToTable("Reserves");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("EasyTime.Model.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpireChangePasswordToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBusinesOwner")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TokenForChangePassword")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EasyTime.Model.Models.UserBusinessOwner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BusinessOnwerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateObjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpire")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateEntityDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserBusinessOwners");
                });

            modelBuilder.Entity("BusinessOwnerDay", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Business", "Business")
                        .WithMany("BusinessOwnerDays")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BusinessOwnerTime", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Business", "Business")
                        .WithMany("BusinessOwnerTimes")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessOwnerDay", "BusinessOwnerDay")
                        .WithMany("BusinessOwnerTimes")
                        .HasForeignKey("BusinessOwnerDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("BusinessOwnerDay");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesNeighberhood", b =>
                {
                    b.HasOne("EasyTime.Model.Models.BusinesRegion", "BusinesRegion")
                        .WithMany()
                        .HasForeignKey("BusinesRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinesRegion");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesRegion", b =>
                {
                    b.HasOne("EasyTime.Model.Models.BusinesCity", "BusinesCity")
                        .WithMany("BusinesRegions")
                        .HasForeignKey("BusinesCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinesCity");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Business", b =>
                {
                    b.HasOne("EasyTime.Model.Models.User", "User")
                        .WithMany("Businesses")
                        .HasForeignKey("BusinessOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyTime.Model.Models.Category", "Category")
                        .WithMany("Businesses")
                        .HasForeignKey("CategoryId");

                    b.HasOne("EasyTime.Model.Models.BusinesCity", "BusinesCity")
                        .WithMany("Businesses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyTime.Model.Models.BusinesNeighberhood", "BusinesNeighberhood")
                        .WithMany("Businesses")
                        .HasForeignKey("NeighberhoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyTime.Model.Models.BusinesRegion", "BusinesRegion")
                        .WithMany("Businesses")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinesCity");

                    b.Navigation("BusinesNeighberhood");

                    b.Navigation("BusinesRegion");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinessDay", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Business", "Business")
                        .WithMany("BusinessDays")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessOwnerDay", "BusinessOwnerDay")
                        .WithMany("BusinessDays")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("BusinessOwnerDay");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinessOwnerPlan", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyTime.Model.Models.PlanTime", "PlanTime")
                        .WithMany("BusinessOwnerPlans")
                        .HasForeignKey("PlanTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyTime.Model.Models.User", "User")
                        .WithMany("BusinessOwnerPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("PlanTime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinessServices", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Business", "Business")
                        .WithMany("BusinessServices")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyTime.Model.Models.Service", "Service")
                        .WithMany("BusinessServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinessTime", b =>
                {
                    b.HasOne("EasyTime.Model.Models.BusinessDay", "BusinessDay")
                        .WithMany("BusinessTimes")
                        .HasForeignKey("BusinessDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessOwnerTime", "BusinessOwnerTime")
                        .WithMany("BusinessTimes")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessDay");

                    b.Navigation("BusinessOwnerTime");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Plan", b =>
                {
                    b.HasOne("EasyTime.Model.Models.PlanTime", null)
                        .WithMany("Plans")
                        .HasForeignKey("PlanTimeId");
                });

            modelBuilder.Entity("EasyTime.Model.Models.PlansInformation", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Plan", "Plan")
                        .WithMany("PlansInformation")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Reserve", b =>
                {
                    b.HasOne("BusinessOwnerDay", "BusinessOwnerDay")
                        .WithMany("Reserves")
                        .HasForeignKey("BusinessOwnerDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessOwnerTime", "BusinessOwnerTime")
                        .WithMany("Reserves")
                        .HasForeignKey("BusinessOwnerTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessOwnerDay");

                    b.Navigation("BusinessOwnerTime");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Service", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EasyTime.Model.Models.User", b =>
                {
                    b.HasOne("EasyTime.Model.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EasyTime.Model.Models.UserBusinessOwner", b =>
                {
                    b.HasOne("EasyTime.Model.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessOwnerDay", b =>
                {
                    b.Navigation("BusinessDays");

                    b.Navigation("BusinessOwnerTimes");

                    b.Navigation("Reserves");
                });

            modelBuilder.Entity("BusinessOwnerTime", b =>
                {
                    b.Navigation("BusinessTimes");

                    b.Navigation("Reserves");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesCity", b =>
                {
                    b.Navigation("BusinesRegions");

                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesNeighberhood", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinesRegion", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Business", b =>
                {
                    b.Navigation("BusinessDays");

                    b.Navigation("BusinessOwnerDays");

                    b.Navigation("BusinessOwnerTimes");

                    b.Navigation("BusinessServices");
                });

            modelBuilder.Entity("EasyTime.Model.Models.BusinessDay", b =>
                {
                    b.Navigation("BusinessTimes");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Category", b =>
                {
                    b.Navigation("Businesses");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Plan", b =>
                {
                    b.Navigation("PlansInformation");
                });

            modelBuilder.Entity("EasyTime.Model.Models.PlanTime", b =>
                {
                    b.Navigation("BusinessOwnerPlans");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EasyTime.Model.Models.Service", b =>
                {
                    b.Navigation("BusinessServices");
                });

            modelBuilder.Entity("EasyTime.Model.Models.User", b =>
                {
                    b.Navigation("BusinessOwnerPlans");

                    b.Navigation("Businesses");
                });
#pragma warning restore 612, 618
        }
    }
}
